# MPD basic config
music_directory    "/home/ayman/sd/music"
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/mpd.db"
log_file           "~/.config/mpd/mpd.log"
pid_file           "~/.config/mpd/mpd.pid"
state_file         "~/.config/mpd/mpdstate"

# Audio output
audio_output {
    type        "alsa"
    name        "My ALSA Device"
    mixer_type  "hardware"
}

# Optional: enable network access (for MPD clients)
# bind_to_address "127.0.0.1"
# port 6600
