#!/bin/bash

# Display OS version and kernel version
echo "Operating System: $(grep PRETTY_NAME /etc/os-release | cut -d '=' -f2 | sed 's/"//g')"
echo "Kernel Version: $(uname -sr)"

# Display hardware information
echo "CPU: $(lscpu | grep 'Model name' | cut -d':' -f2 | awk '{$1=$1};1')"
echo "RAM: $(free -h | awk '/^Mem:/{print $2}')"
echo "GPU: $(lspci | grep VGA | cut -d ":" -f3)"

# flag to display installed software
# q flag to show packages names without version infos
# e flag to exclude packages installed as dependencies
if [ "$1" == "-s" ]; then
  echo "Installed software:"
  pacman -Qqe | awk '{$1=$1};1'
fi

# flag to display storage information
if [ "$1" == "-st" ]; then
  echo "Storage Information:"
  df -h | awk '/^\/dev/{print "Drive:",$1,"\nTotal Size:",$2,"\nUsed:",$3,"\nFree:",$4,"\n"}'
fi

