#!/bin/sh

if pgrep -x "dunst" > /dev/null
then
    volume=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

    if [ "$1" = "up" ]; then
        pactl -- set-sink-volume 0 +10%
    elif [ "$1" = "down" ]; then
        pactl -- set-sink-volume 0 -10%
   fi

    dunstify -a "volume" -u low -t 2000 "Volume: $volume%"
else
    echo "dunst is not running !!"
fi
